name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - run: curl https://cn.bing.com`curl cn.bing.com|grep preload|cut -d \" -f 6|cut -d \& -f 1` -o latest.jpg
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
