name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install jq
      - run: bash main
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add .
      - run: git commit -m "Add BingPic"
      - run: git push origin master
