name: CI
on:
  schedule:
    - cron: '0 16 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: mkdir latest
      - run: curl -s https://bing.com`curl -G -d 'format=js&n=1&mkt=zh-CN' -s https://bing.com/HPImageArchive.aspx | jq -r '.images[0].url'` -o latest/zh_CN.jpeg
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add BingPic"
          git push origin master
